parameters:
    database_driver:   pdo_sqlite
    database_host:     ""
    database_port:     ""
    database_name:     photobooth
    database_user:     photobooth
    database_password: photobooth
    database_path:     data.sqlite

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            fgdhrth085tuk45jkhhftuw87238i4rhgjh34rgj

