NickyDigitalPhotoboothAdminBundle_admin_nicky_digital_photobooth_admin_bundle:
    resource: "@NickyDigitalPhotoboothAdminBundle/Controller/"
    type:     admingenerator
    prefix:   /admin

nicky_digital_photobooth:
    resource: "@NickyDigitalPhotoboothBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
