generator: admingenerator.generator.doctrine
params:
  model: NickyDigital\PhotoboothBundle\Entity\PhotoEvent
  namespace_prefix: NickyDigital
  bundle_name: PhotoboothAdminBundle
  fields:
    eventCode:
      label: Code
    eventName:
      label: Name
    folder:
      label: Folder
    albumName:
      label: Facebook Album Name
    albumDesc:
      label: Facebook Album Description
    thumbAspect:
      label: Thumb Aspect Ratio
      formType: choice
      addFormOptions:
        choices:
          portrait: Portrait
          landscape: Landscape
          square: Square
    shortShareText:
      label: Twitter Share Text
    longShareText:
      label: Facebook Share Text
    emailShareSubject:
      label: Email Share Subject
    emailShareText:
      label: Email Share Text
    tumblrShareText:
      label: Tumblr Share Text
    tumblrTags:
      label: Tumblr Tags
    tumblrUrl:
      label: Tumblr Url
    current:
      label: Is Current
    showFacebook:
      label: Show Facebook Button
    showTwitter:
      label: Show Twitter Button
    showTumblr:
      label: Show Tumblr Button
    showEmail:
      label: Show Email Button
    showWaterfall:
      label: Show Waterfall
    showFacebookLike:
      label: Show Facebook Like
    facebookLikeText:
      label: Facebook Like Text
    facebookLikeUrl:
      label: Facebook Like URL
    facebookConsumerKey:
      label: Facebook Consumer Key
    facebookConsumerSecret:
      label: Facebook Consumer Secret
    twitterConsumerKey:
      label: Twitter Consumer Key
    twitterConsumerSecret:
      label: Twitter Consumer Secret
    tumblrConsumerKey:
      label: Tumblr Consumer Key
    tumblrConsumerSecret:
      label: Tumblr Consumer Secret
    
builders:
  list:
    params:
      title: Events
      display: [id, eventCode, eventName, albumName, current]
      actions:
        new: ~
      object_actions:
        show: ~
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New Event
      display: [eventCode, eventName, folder, thumbAspect, albumName, albumDesc, shortShareText, longShareText, emailShareSubject, emailShareText, tumblrShareText, tumblrTags, tumblrUrl, current, showFacebook, showTwitter, showTumblr, showEmail, showWaterfall, showFacebookLike, facebookLikeText, facebookLikeUrl, facebookConsumerKey, facebookConsumerSecret, twitterConsumerKey, twitterConsumerSecret, tumblrConsumerKey, tumblrConsumerSecret ]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing the object \"%object%\"|{ %object%: PhotoEvent.eventName }|"
      display: [eventCode, eventName, folder, thumbAspect, albumName, albumDesc, shortShareText, longShareText, emailShareSubject, emailShareText, tumblrShareText, tumblrTags, tumblrUrl, current, showFacebook, showTwitter, showTumblr, showEmail, showWaterfall, showFacebookLike, facebookLikeText, facebookLikeUrl, facebookConsumerKey, facebookConsumerSecret, twitterConsumerKey, twitterConsumerSecret, tumblrConsumerKey, tumblrConsumerSecret ]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: PhotoEvent.eventName }|"
      display: [eventCode, eventName, thumbAspect, albumName, albumDesc, current ]
      actions:
        list: ~
        edit: ~
        new: ~
      object_actions: ~
  delete: ~
