generator: admingenerator.generator.doctrine
params:
  model: NickyDigital\PhotoboothBundle\Entity\PhotoEvent
  namespace_prefix: NickyDigital
  bundle_name: PhotoboothAdminBundle
  fields: id, eventName, current

builders:
  list:
    params:
      title: Events
      display: [id, eventCode, eventName, albumName]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New Event
      display: [eventCode, eventName, albumName, shortShareText, longShareText, current ]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing the object \"%object%\"|{ %object%: PhotoEvent.eventName }|"
      display: [eventCode, eventName, albumName, shortShareText, longShareText, current ]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: PhotoEvent.eventName }|"
      display: [eventCode, eventName, albumName, shortShareText, longShareText, current ]
      actions:
        list: ~
        new: ~
      object_actions: ~
  delete: ~
